package protocatalyst.encoder.spark.arrow

import java.nio.ByteBuffer
import java.nio.file.{Files, Paths}
import java.{sql => jsql}
import java.math.{BigDecimal => JBigDecimal}
import java.time.{Duration, Instant, LocalDate, LocalDateTime, Period}

import scala.jdk.CollectionConverters.*

import munit.FunSuite
import org.apache.arrow.vector.types.pojo.Schema

import protocatalyst.encoder.spark.tpch.Schemas.*

/** Byte-level parity of [[ArrowSchemaBuilders.schemaFor]] against Spark 4.1.2's
  * `ArrowUtils.toArrowSchema(enc.schema, ...)`.
  *
  * Fixtures live in `src/test/resources/arrow-schema-parity/` and are regenerated by
  * {{{ sbt 'benchmarkSpark/runMain org.apache.spark.sql.protocatalyst.ArrowSchemaParityFixtures' }}}.
  *
  * Case-class shapes here MUST stay structurally identical to those in
  * `benchmark-spark/.../ArrowSchemaParityFixtures.scala`. Both files reference the same TPC-H
  * schemas (mirrored across modules); only the per-variant fixtures need local mirrors.
  *
  * NOTE on coverage: `LocalTime` is supported by `ArrowSchemaBuilders` but excluded from parity
  * because Spark 4.1.2's `ExpressionEncoder` rejects `TimeType` at serializer-construction time
  * (`[UNSUPPORTED_TIME_TYPE]`), even though the AgnosticEncoder hierarchy includes
  * `LocalTimeEncoder`. There is no Spark counterpart to compare against.
  */
class ArrowSchemaParitySpec extends FunSuite:

  // ---------------------------------------------------------------------------
  // Per-variant case classes — structural mirror of the Scala 2.13 fixture file.
  // ---------------------------------------------------------------------------

  case class Simple(id: Int, name: String)
  case class AllPrimitives(
      b: Boolean,
      i8: Byte,
      i16: Short,
      i32: Int,
      i64: Long,
      f32: Float,
      f64: Double
  )
  case class Strings(s: String, b: Array[Byte])
  case class Decimals(s: BigDecimal, j: JBigDecimal)
  case class Temporal(
      d: LocalDate,
      sd: jsql.Date,
      i: Instant,
      st: jsql.Timestamp,
      ldt: LocalDateTime,
      dur: Duration,
      per: Period
  )
  case class Optional(oi: Option[Int], os: Option[String], od: Option[LocalDate])

  // ---------------------------------------------------------------------------
  // Helpers.
  // ---------------------------------------------------------------------------

  private val fixtureDir = "encoder-spark/src/test/resources/arrow-schema-parity"

  private def loadFixture(name: String): Array[Byte] = {
    val path = Paths.get(fixtureDir, s"$name.arrow-schema")
    if !Files.exists(path) then
      fail(
        s"Missing fixture $path — regenerate with " +
          "`sbt 'benchmarkSpark/runMain org.apache.spark.sql.protocatalyst.ArrowSchemaParityFixtures'`"
      )
    Files.readAllBytes(path)
  }

  private def assertParity(
      name: String,
      ours: Schema,
      hint: String = ""
  ): Unit = {
    val expectedBytes = loadFixture(name)
    val expected = Schema.deserializeMessage(ByteBuffer.wrap(expectedBytes))
    val actualBytes = ours.serializeAsMessage()
    // Compare bytes first (deterministic flatbuffer encoding); on mismatch produce a useful diff.
    if !java.util.Arrays.equals(expectedBytes, actualBytes) then
      val fieldDiff =
        if expected.getFields.size != ours.getFields.size then
          s"field count: expected=${expected.getFields.size}, actual=${ours.getFields.size}"
        else
          expected.getFields.asScala.zip(ours.getFields.asScala).zipWithIndex
            .map { case ((e, a), i) =>
              val diffs = List(
                if e.getName != a.getName then Some(s"name (${e.getName} vs ${a.getName})") else None,
                if e.isNullable != a.isNullable then
                  Some(s"nullable (${e.isNullable} vs ${a.isNullable})")
                else None,
                if e.getType != a.getType then
                  Some(s"type (${e.getType} vs ${a.getType})")
                else None
              ).flatten
              if diffs.isEmpty then None else Some(s"  [$i]: ${diffs.mkString(", ")}")
            }
            .flatten
            .mkString("\n")
      fail(
        s"$name schema parity failure${if hint.nonEmpty then s" ($hint)" else ""}\n" +
          s"expected ${expectedBytes.length}B vs actual ${actualBytes.length}B\n" +
          (if fieldDiff.nonEmpty then s"field diff:\n$fieldDiff" else "")
      )
  }

  // ---------------------------------------------------------------------------
  // Per-variant tests.
  // ---------------------------------------------------------------------------

  test("Simple: schema parity"):
    assertParity("Simple", ArrowSchemaBuilders.schemaFor[Simple])

  test("AllPrimitives: schema parity"):
    assertParity("AllPrimitives", ArrowSchemaBuilders.schemaFor[AllPrimitives])

  test("Strings: schema parity (Utf8/Binary default)"):
    assertParity("Strings", ArrowSchemaBuilders.schemaFor[Strings])

  test("Strings: schema parity (LargeUtf8/LargeBinary with largeVarTypes=true)"):
    assertParity(
      "Strings-largeVarTypes",
      ArrowSchemaBuilders.schemaFor[Strings]("UTC", true)
    )

  test("Decimals: schema parity"):
    assertParity("Decimals", ArrowSchemaBuilders.schemaFor[Decimals])

  test("Temporal: schema parity (no LocalTime)"):
    assertParity("Temporal", ArrowSchemaBuilders.schemaFor[Temporal])

  test("Optional: schema parity (Option[Int/String/LocalDate])"):
    assertParity("Optional", ArrowSchemaBuilders.schemaFor[Optional])

  // ---------------------------------------------------------------------------
  // TPC-H schemas — the workhorse parity surface for the report's headline claim.
  // ---------------------------------------------------------------------------

  test("TPC-H Region: schema parity"):
    assertParity("tpch-Region", ArrowSchemaBuilders.schemaFor[Region])

  test("TPC-H Nation: schema parity"):
    assertParity("tpch-Nation", ArrowSchemaBuilders.schemaFor[Nation])

  test("TPC-H Part: schema parity"):
    assertParity("tpch-Part", ArrowSchemaBuilders.schemaFor[Part])

  test("TPC-H Supplier: schema parity"):
    assertParity("tpch-Supplier", ArrowSchemaBuilders.schemaFor[Supplier])

  test("TPC-H PartSupp: schema parity"):
    assertParity("tpch-PartSupp", ArrowSchemaBuilders.schemaFor[PartSupp])

  test("TPC-H Customer: schema parity"):
    assertParity("tpch-Customer", ArrowSchemaBuilders.schemaFor[Customer])

  test("TPC-H Orders: schema parity"):
    assertParity("tpch-Orders", ArrowSchemaBuilders.schemaFor[Orders])

  test("TPC-H Lineitem: schema parity (16 columns, workhorse case)"):
    assertParity("tpch-Lineitem", ArrowSchemaBuilders.schemaFor[Lineitem])
