package protocatalyst.encoder.spark

import java.nio.file.{Files, Paths}

import munit.FunSuite
import org.apache.spark.sql.catalyst.encoders.{AgnosticEncoder, ExpressionEncoder}
import org.apache.spark.sql.catalyst.encoders.AgnosticEncoders.*

import protocatalyst.encoder.ProtoEncoder

// Top-level (NOT nested in the spec class): Spark's NewInstance needs an outer-scope pointer for
// inner classes; top-level types have `outerPointerGetter = None`, matching our bridge. Structural
// mirror of AgnosticParityFixtures.Person.
case class Person(id: Int, name: String, active: Boolean, score: Double)

// M1 leaf-coverage corpus — structural mirrors of AgnosticParityFixtures.
case class Primitives(b: Boolean, by: Byte, sh: Short, i: Int, l: Long, f: Float, d: Double)
case class Boxed(
    b: java.lang.Boolean,
    by: java.lang.Byte,
    sh: java.lang.Short,
    i: java.lang.Integer,
    l: java.lang.Long,
    f: java.lang.Float,
    d: java.lang.Double
)
case class Scalars(
    s: String,
    bin: Array[Byte],
    dec: BigDecimal,
    jdec: java.math.BigDecimal,
    bi: BigInt,
    jbi: java.math.BigInteger
)
case class Temporal(
    ld: java.time.LocalDate,
    sd: java.sql.Date,
    inst: java.time.Instant,
    ts: java.sql.Timestamp,
    ldt: java.time.LocalDateTime,
    dur: java.time.Duration,
    per: java.time.Period
)

// M2 recursive corpus — mirrors AgnosticParityFixtures.
case class Address(street: String, zip: Int)
case class Opts(oi: Option[Int], os: Option[String], od: Option[java.time.LocalDate])
case class Colls(ints: Seq[Int], strs: List[String], vec: Vector[Long], set: Set[Int], arr: Array[Double])
case class Maps(m1: Map[String, Int], m2: Map[Int, String])
case class Nested(id: Int, addr: Address)
// `nums: Seq[Option[Int]]` exercises a collection of a nullable wrapper (still leaf-backed).
case class Wrapped(id: Int, nums: Seq[Option[Int]])
// Collection/map/option OF a case class — derivable after the inline-given ProtoEncoder fix.
case class Deep(id: Int, tags: Seq[Address], lookup: Map[String, Address], maybe: Option[Address])

/** M0 spike for the reflection-replacement initiative (see docs/REFLECTION_REPLACEMENT.md):
  *
  *   1. **Structural parity** — `AgnosticEncoderBridge.toAgnostic(ProtoEncoder.derived[T])`
  *      produces the same `AgnosticEncoder` shape Spark's reflective `ScalaReflection.encoderFor`
  *      does (golden generated by `AgnosticParityFixtures` on the Scala 2.13 side, since
  *      `encoderFor[T: TypeTag]` doesn't exist on Scala 3).
  *   2. **Round-trip** — `ExpressionEncoder` built from *our* `AgnosticEncoder` serializes and
  *      deserializes correctly through Spark's own codegen — proving the bridge yields a working
  *      encoder, derived from Scala 3 with **zero `TypeTag` / zero Scala reflection**.
  */
class AgnosticEncoderBridgeSpec extends FunSuite:

  /** Canonical, class-name-normalized structural dump — identical logic to the 2.13 generator. */
  private def canonical(e: AgnosticEncoder[?]): String = e match
    case p: ProductEncoder[?] =>
      "Product[" + p.clsTag.runtimeClass.getSimpleName + "](" +
        p.fields
          .map(f => f.name + ":" + canonical(f.enc) + (if f.nullable then "?" else "!"))
          .mkString(",") + ")"
    case o: OptionEncoder[?]      => "Option[" + canonical(o.elementEncoder) + "]"
    case a: ArrayEncoder[?]       => "Array[" + canonical(a.element) + ",cn=" + a.containsNull + "]"
    case i: IterableEncoder[?, ?] =>
      "Iterable[" + i.clsTag.runtimeClass.getSimpleName + "," + canonical(i.element) +
        ",cn=" + i.containsNull + "]"
    case m: MapEncoder[?, ?, ?] =>
      "Map[" + canonical(m.keyEncoder) + "," + canonical(m.valueEncoder) +
        ",vcn=" + m.valueContainsNull + "]"
    // Parametric leaves: capture precision/scale and lenientSerialization so the dump is rigorous.
    case d: ScalaDecimalEncoder => s"ScalaDecimal(${d.dt.precision},${d.dt.scale})"
    case d: JavaDecimalEncoder  =>
      s"JavaDecimal(${d.dt.precision},${d.dt.scale},len=${d.lenientSerialization})"
    case d: SparkDecimalEncoder => s"SparkDecimal(${d.dt.precision},${d.dt.scale})"
    case e: DateEncoder         => s"Date(len=${e.lenientSerialization})"
    case e: LocalDateEncoder    => s"LocalDate(len=${e.lenientSerialization})"
    case e: TimestampEncoder    => s"Timestamp(len=${e.lenientSerialization})"
    case e: InstantEncoder      => s"Instant(len=${e.lenientSerialization})"
    case c: CharEncoder         => s"Char(${c.length})"
    case v: VarcharEncoder      => s"Varchar(${v.length})"
    case leaf                   => leaf.getClass.getSimpleName.stripSuffix("$")

  private def loadGolden(name: String): String =
    val path = Paths.get("encoder-spark/src/test/resources/agnostic-parity", s"$name.agnostic")
    if !Files.exists(path) then
      fail(
        s"Missing golden $path — regenerate with " +
          "`sbt 'benchmarkSpark/runMain org.apache.spark.sql.protocatalyst.AgnosticParityFixtures'`"
      )
    new String(Files.readAllBytes(path)).trim

  /** Derive `T` at compile time, lower via the bridge, assert the canonical dump matches the
    * Scala 2.13 golden. `inline` because `ProtoEncoder.derived` needs the `Mirror` at the call site.
    */
  private inline def assertParity[T](name: String)(using
      m: scala.deriving.Mirror.Of[T]
  ): Unit =
    assertEquals(canonical(AgnosticEncoderBridge.toAgnostic(ProtoEncoder.derived[T])), loadGolden(name))

  test("structural parity: Person (flat)"):
    assertParity[Person]("Person")

  test("structural parity: Primitives (7 unboxed, non-nullable)"):
    assertParity[Primitives]("Primitives")

  test("structural parity: Boxed (7 boxed, nullable)"):
    assertParity[Boxed]("Boxed")

  test("structural parity: Scalars (String/Binary/Scala+Java Decimal/BigInt)"):
    assertParity[Scalars]("Scalars")

  test("structural parity: Temporal (Date/LocalDate/Timestamp/Instant/LocalDateTime/Duration/Period)"):
    assertParity[Temporal]("Temporal")

  test("structural parity: Opts (Option of leaves)"):
    assertParity[Opts]("Opts")

  test("structural parity: Colls (Seq/List/Vector/Set/Array)"):
    assertParity[Colls]("Colls")

  test("structural parity: Maps (Map[String,Int], Map[Int,String])"):
    assertParity[Maps]("Maps")

  test("structural parity: Nested (struct of struct)"):
    assertParity[Nested]("Nested")

  test("structural parity: Wrapped (Seq[Option[Int]])"):
    assertParity[Wrapped]("Wrapped")

  test("structural parity: Deep (Seq/Map/Option of a case class — engine-gap fix)"):
    assertParity[Deep]("Deep")

  test("ExpressionEncoder builds from our AgnosticEncoder; schema is reflection-free & Spark-correct"):
    val ours = AgnosticEncoderBridge.toAgnostic(ProtoEncoder.derived[Person])
    val enc = ExpressionEncoder(ours)
    // The schema (DataType) is reflection-free — sanity that the encoder is well-formed and that
    // the corrected nullability (name nullable, primitives not) lands. This is the furthest the
    // pipeline runs from a Scala 3 process against *stock* Spark (see note below).
    assertEquals(
      enc.schema.fields.map(f => s"${f.name}:${f.dataType.typeName}:${f.nullable}").mkString(","),
      "id:integer:false,name:string:true,active:boolean:false,score:double:false"
    )

  // FINDING (M0): actually *executing* ser/deser from this Scala 3 process against stock Spark
  // crashes — `Invoke.encodedFunctionName` calls `ScalaReflection.encodeFieldNameToIdentifier`
  // (`TermName(name).encodedName`, a scala.reflect.runtime use), and touching the `ScalaReflection`
  // object eagerly initializes `val universe = scala.reflect.runtime.universe`, which cannot
  // initialize against the Scala 3 stdlib (`FatalError: class Array does not have a member apply`).
  // This refutes "everything downstream of AgnosticEncoder is reflection-free" and is itself the
  // thesis in miniature: stock Spark cannot run on Scala 3. Behavioral correctness here follows
  // from the structural-parity test above (our AgnosticEncoder == Spark's ⇒ identical Spark
  // expressions/codegen ⇒ identical behavior); end-to-end execution is for a Scala-3-ported Spark.
