package protocatalyst.catalyst.e2e

import java.nio.file.{Files, Paths}

import org.apache.spark.sql.SparkSession

import protocatalyst.catalyst.SparkQueryRunner

/** End-to-end integration tests for the full ProtoCatalyst pipeline.
  *
  * Loads PCAT artifacts generated by the Scala 3 `E2EArtifactGenerator` (via `quote {}` and
  * `CompiledQuery.sqlOptimized`) and executes them against real Spark DataFrames.
  *
  * This proves the complete path: compile-time DSL/SQL → ProtoLogicalPlan → optimize → serialize to
  * PCAT bytes → deserialize in Scala 2.13 → Spark LogicalPlan → DataFrame execution.
  *
  * Prerequisites: Run `sbt "query/Test/runMain protocatalyst.e2e.E2EArtifactGenerator"` first.
  */
class E2EIntegrationSuite extends munit.FunSuite {

  private var spark: SparkSession = _

  override def beforeAll(): Unit = {
    spark = SparkSession
      .builder()
      .master("local[1]")
      .appName("E2EIntegrationTest")
      .config("spark.ui.enabled", "false")
      .config("spark.sql.shuffle.partitions", "1")
      .config("spark.driver.host", "localhost")
      .config("spark.driver.bindAddress", "127.0.0.1")
      .getOrCreate()

    // QuoteUser(name: String, age: Int, salary: Double)
    spark.sql(
      """CREATE OR REPLACE TEMP VIEW users AS
        |SELECT * FROM VALUES
        |  ('Alice', 30, 80000.0),
        |  ('Bob', 25, 65000.0),
        |  ('Carol', 35, 90000.0),
        |  ('Dave', 22, 55000.0),
        |  ('Eve', 28, 75000.0)
        |AS users(name, age, salary)""".stripMargin
    )
  }

  override def afterAll(): Unit = {
    if (spark != null) {
      spark.stop()
    }
  }

  // === Helpers ===

  private def loadArtifact(id: String): Array[Byte] = {
    val possiblePaths = Seq(
      s"spark-catalyst/src/test/resources/e2e-artifacts/$id.pcat",
      s"src/test/resources/e2e-artifacts/$id.pcat",
      s"../spark-catalyst/src/test/resources/e2e-artifacts/$id.pcat"
    )
    possiblePaths
      .map(Paths.get(_))
      .find(Files.exists(_))
      .map(Files.readAllBytes(_))
      .getOrElse {
        assume(
          false,
          s"Artifact $id.pcat not found. Run: sbt \"query/Test/runMain protocatalyst.e2e.E2EArtifactGenerator\""
        )
        throw new AssertionError("unreachable")
      }
  }

  // === DSL path tests ===

  test("e2e: dsl_table_scan — full table scan") {
    val bytes = loadArtifact("dsl_table_scan")
    val df = SparkQueryRunner.execute(bytes, spark)
    assert(df.count() == 5)
    val names = df.collect().map(_.getAs[String]("name")).sorted.toSeq
    assert(names == Seq("Alice", "Bob", "Carol", "Dave", "Eve"))
  }

  test("e2e: dsl_filter_gt — filter age > 25") {
    val bytes = loadArtifact("dsl_filter_gt")
    val df = SparkQueryRunner.execute(bytes, spark)
    assert(df.count() == 3)
    val names = df.collect().map(_.getAs[String]("name")).sorted.toSeq
    assert(names == Seq("Alice", "Carol", "Eve"))
  }

  test("e2e: dsl_filter_limit — filter salary >= 70000 then limit 2") {
    val bytes = loadArtifact("dsl_filter_limit")
    val df = SparkQueryRunner.execute(bytes, spark)
    assert(df.count() == 2)
    // All returned rows should have salary >= 70000
    val salaries = df.collect().map(r => r.get(r.fieldIndex("salary")).toString.toDouble)
    salaries.foreach(s => assert(s >= 70000.0, s"Expected salary >= 70000, got $s"))
  }

  test("e2e: dsl_distinct — all rows are unique") {
    val bytes = loadArtifact("dsl_distinct")
    val df = SparkQueryRunner.execute(bytes, spark)
    assert(df.count() == 5)
  }

  test("e2e: dsl_string_eq — filter name === Alice") {
    val bytes = loadArtifact("dsl_string_eq")
    val df = SparkQueryRunner.execute(bytes, spark)
    assert(df.count() == 1)
    val name = df.collect()(0).getAs[String]("name")
    assert(name == "Alice")
  }

  // === SQL path tests ===

  test("e2e: sql_select_where — SELECT name, age WHERE age > 25") {
    val bytes = loadArtifact("sql_select_where")
    val df = SparkQueryRunner.execute(bytes, spark)
    assert(df.count() == 3)
    val columns = df.columns.toSeq
    assert(columns.contains("name"), s"Expected 'name' column, got: $columns")
    assert(columns.contains("age"), s"Expected 'age' column, got: $columns")
    val names = df.collect().map(_.getAs[String]("name")).sorted.toSeq
    assert(names == Seq("Alice", "Carol", "Eve"))
  }

  test("e2e: sql_order_limit — ORDER BY salary DESC LIMIT 3") {
    val bytes = loadArtifact("sql_order_limit")
    val df = SparkQueryRunner.execute(bytes, spark)
    assert(df.count() == 3)
    val rows = df.collect()
    // Carol(90000), Alice(80000), Eve(75000)
    assert(rows(0).getAs[String]("name") == "Carol")
    assert(rows(1).getAs[String]("name") == "Alice")
    assert(rows(2).getAs[String]("name") == "Eve")
  }

  test("e2e: sql_arithmetic — salary + 1000 WHERE age >= 28") {
    val bytes = loadArtifact("sql_arithmetic")
    val df = SparkQueryRunner.execute(bytes, spark)
    // age >= 28: Alice(30), Carol(35), Eve(28)
    assert(df.count() == 3)
    val names = df.collect().map(_.getAs[String]("name")).sorted.toSeq
    assert(names == Seq("Alice", "Carol", "Eve"))
  }
}
