package protocatalyst.truffle;

import com.oracle.truffle.api.CallTarget;
import com.oracle.truffle.api.Truffle;
import com.oracle.truffle.api.nodes.RootNode;

/**
 * Phase-0 probe (see {@code docs/compiler/TRUFFLE_EXPLORATION.md} §4 Phase 0).
 *
 * <p>Two things this answers empirically:
 * <ol>
 *   <li><b>Does the DSL toolchain work in our build?</b> If this runs at all, {@code AddNodeGen}
 *       was generated by the annotation processor and the node executes correctly.</li>
 *   <li><b>Do we get the optimizing runtime?</b> {@link com.oracle.truffle.api.TruffleRuntime#getName()}
 *       reports {@code "Optimized Truffle Runtime"} when Graal partial-evaluation/JIT is active
 *       (GraalVM JDK, or a stock JDK with the jargraal {@code truffle-runtime} + JVMCI enabled), and
 *       a default/interpreter name otherwise. This is the GraalVM-vs-stock-JDK decision, measured.</li>
 * </ol>
 *
 * Run: {@code sbt truffleExec/run}. To watch partial evaluation when the optimizing runtime is
 * present, add {@code -Dpolyglot.engine.TraceCompilation=true} to the JVM args.
 */
public final class HelloTruffle {

    public static void main(String[] args) {
        System.out.println("Truffle runtime : " + Truffle.getRuntime().getName());

        RootNode root = new HelloRootNode(null);
        CallTarget target = root.getCallTarget();

        // Exercise the call target enough to trip the compilation threshold if the optimizing
        // runtime is active. Checksum prevents the loop from being optimized away.
        long checksum = 0;
        for (int i = 0; i < 2_000_000; i++) {
            checksum += (long) target.call(3L, (long) i);
        }

        System.out.println("warmup checksum : " + checksum);
        System.out.println("3 + 4           : " + target.call(3L, 4L));
    }
}
