package protocatalyst.catalyst.parity

import java.nio.file.{Files, Paths}

import scala.jdk.CollectionConverters._

import org.apache.spark.sql.SparkSession

/** Integration tests that verify parity between ProtoCatalyst and Spark SQL parser.
  *
  * These tests read JSON artifacts generated by ProtoCatalyst's Scala 3 code and compare them
  * against Spark's own SQL parser output.
  */
class IntegrationParitySuite extends munit.FunSuite {

  // Shared SparkSession for all tests
  private var spark: SparkSession = _

  override def beforeAll(): Unit = {
    spark = SparkSession
      .builder()
      .master("local[1]")
      .appName("IntegrationParityTest")
      .config("spark.ui.enabled", "false")
      .config("spark.sql.shuffle.partitions", "1")
      .config("spark.driver.host", "localhost")
      .config("spark.driver.bindAddress", "127.0.0.1")
      .getOrCreate()
  }

  override def afterAll(): Unit = {
    if (spark != null) {
      spark.stop()
    }
  }

  /** Read test artifacts from resources directory */
  private def loadTestArtifacts(): Seq[(String, String, String)] = {
    // Try multiple possible locations for artifacts
    val possiblePaths = Seq(
      "spark-catalyst/src/test/resources/parity-artifacts",
      "src/test/resources/parity-artifacts",
      "../spark-catalyst/src/test/resources/parity-artifacts"
    )

    val resourceDir = possiblePaths
      .map(Paths.get(_))
      .find(p => Files.exists(p) && Files.isDirectory(p))

    if (resourceDir.isEmpty) {
      println(s"Searched paths: ${possiblePaths.mkString(", ")}")
      println(s"Working directory: ${System.getProperty("user.dir")}")
      Seq.empty
    } else {
      val dir = resourceDir.get
      println(s"Found artifacts at: $dir")
      val jsonFiles = Files
        .list(dir)
        .iterator()
        .asScala
        .filter(p => p.toString.endsWith(".json"))
        .toSeq

      jsonFiles.flatMap { jsonPath =>
        val id = jsonPath.getFileName.toString.stripSuffix(".json")
        val sqlPath = dir.resolve(s"$id.sql")

        if (Files.exists(sqlPath)) {
          val json = Files.readString(jsonPath)
          val sql = Files.readString(sqlPath).trim
          Some((id, sql, json))
        } else {
          None
        }
      }
    }
  }

  test("integration parity tests from artifacts") {
    implicit val s: SparkSession = spark

    val artifacts = loadTestArtifacts()

    if (artifacts.isEmpty) {
      // Skip if no artifacts exist yet
      println("No parity artifacts found. Run ParityArtifactGenerator first.")
    } else {

      println(s"Running ${artifacts.size} parity tests...")

      var passed = 0
      var failed = 0
      val failures = scala.collection.mutable.ListBuffer[(String, String, Seq[String])]()

      for ((id, sql, json) <- artifacts) {
        try {
          val result = ParityTester.testParity(sql, json)

          if (result.matches) {
            passed += 1
          } else {
            failed += 1
            failures += ((id, sql, result.differences))
          }
        } catch {
          case e: Exception =>
            failed += 1
            failures += ((id, sql, Seq(s"Exception: ${e.getMessage}")))
        }
      }

      println(s"\n=== Parity Test Results ===")
      println(s"Passed: $passed")
      println(s"Failed: $failed")
      println(s"Total:  ${artifacts.size}")

      if (failures.nonEmpty) {
        println("\n=== Failures ===")
        for ((id, sql, diffs) <- failures) {
          println(s"\n[$id] $sql")
          diffs.foreach(d => println(s"  - $d"))
        }
      }

      // For now, we report results but don't fail the test
      // This allows us to iterate on improving parity
      // assert(failed == 0, s"$failed parity tests failed")
    }
  }

  // Individual tests for debugging specific SQL patterns

  test("parity: simple SELECT star") {
    implicit val s: SparkSession = spark
    val sql = "SELECT * FROM users"
    val json =
      """{"plan":{"$type":"protocatalyst.plan.ProtoLogicalPlan.RelationRef","name":"users","alias":null,"schema":{"tableName":"users","fields":[],"fingerprint":0}}}"""

    val result = ParityTester.testParity(sql, json)
    // May not match exactly due to resolution differences
    // assert(result.matches, s"Differences: ${result.differences.mkString(", ")}")
  }

  test("parity: SELECT with projection") {
    implicit val s: SparkSession = spark
    val sql = "SELECT name FROM users"

    // Minimal JSON that should parse
    val json =
      """{
        |  "plan": {
        |    "$type": "protocatalyst.plan.ProtoLogicalPlan.Project",
        |    "projectList": [
        |      {
        |        "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |        "name": "name",
        |        "qualifier": null,
        |        "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |        "nullable": true
        |      }
        |    ],
        |    "child": {
        |      "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |      "name": "users",
        |      "alias": null,
        |      "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |    }
        |  }
        |}""".stripMargin

    val result = ParityTester.testParity(sql, json)
    assert(result.protoPlan != null)
    assert(result.sparkPlan != null)
  }

  test("parity: SELECT with WHERE clause") {
    implicit val s: SparkSession = spark
    val sql = "SELECT name FROM users WHERE age > 18"

    val json =
      """{
        |  "plan": {
        |    "$type": "protocatalyst.plan.ProtoLogicalPlan.Project",
        |    "projectList": [
        |      {
        |        "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |        "name": "name",
        |        "qualifier": null,
        |        "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |        "nullable": true
        |      }
        |    ],
        |    "child": {
        |      "$type": "protocatalyst.plan.ProtoLogicalPlan.Filter",
        |      "condition": {
        |        "$type": "protocatalyst.expr.ProtoExpr.Gt",
        |        "left": {
        |          "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |          "name": "age",
        |          "qualifier": null,
        |          "dataType": {"$type": "protocatalyst.types.ProtoType.IntegerType"},
        |          "nullable": false
        |        },
        |        "right": {
        |          "$type": "protocatalyst.expr.ProtoExpr.Literal",
        |          "value": {"$type": "protocatalyst.expr.LiteralValue.IntValue", "value": 18}
        |        }
        |      },
        |      "child": {
        |        "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |        "name": "users",
        |        "alias": null,
        |        "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |      }
        |    }
        |  }
        |}""".stripMargin

    val result = ParityTester.testParity(sql, json)
    assert(result.protoPlan != null)
    assert(result.sparkPlan != null)
  }

  test("parity: SELECT with ORDER BY") {
    implicit val s: SparkSession = spark
    val sql = "SELECT name, age FROM users ORDER BY age DESC"

    val json =
      """{
        |  "plan": {
        |    "$type": "protocatalyst.plan.ProtoLogicalPlan.Sort",
        |    "order": [
        |      {
        |        "child": {
        |          "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |          "name": "age",
        |          "qualifier": null,
        |          "dataType": {"$type": "protocatalyst.types.ProtoType.IntegerType"},
        |          "nullable": false
        |        },
        |        "direction": "Descending",
        |        "nullOrdering": "NullsLast"
        |      }
        |    ],
        |    "global": true,
        |    "child": {
        |      "$type": "protocatalyst.plan.ProtoLogicalPlan.Project",
        |      "projectList": [
        |        {
        |          "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |          "name": "name",
        |          "qualifier": null,
        |          "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |          "nullable": true
        |        },
        |        {
        |          "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |          "name": "age",
        |          "qualifier": null,
        |          "dataType": {"$type": "protocatalyst.types.ProtoType.IntegerType"},
        |          "nullable": false
        |        }
        |      ],
        |      "child": {
        |        "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |        "name": "users",
        |        "alias": null,
        |        "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |      }
        |    }
        |  }
        |}""".stripMargin

    val result = ParityTester.testParity(sql, json)
    assert(result.protoPlan != null)
    assert(result.sparkPlan != null)
  }

  test("parity: SELECT with LIMIT") {
    implicit val s: SparkSession = spark
    val sql = "SELECT name FROM users LIMIT 10"

    val json =
      """{
        |  "plan": {
        |    "$type": "protocatalyst.plan.ProtoLogicalPlan.Limit",
        |    "limit": 10,
        |    "child": {
        |      "$type": "protocatalyst.plan.ProtoLogicalPlan.Project",
        |      "projectList": [
        |        {
        |          "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |          "name": "name",
        |          "qualifier": null,
        |          "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |          "nullable": true
        |        }
        |      ],
        |      "child": {
        |        "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |        "name": "users",
        |        "alias": null,
        |        "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |      }
        |    }
        |  }
        |}""".stripMargin

    val result = ParityTester.testParity(sql, json)
    assert(result.protoPlan != null)
    assert(result.sparkPlan != null)
  }

  test("parity: GROUP BY with COUNT") {
    implicit val s: SparkSession = spark
    val sql = "SELECT name, COUNT(*) FROM users GROUP BY name"

    val json =
      """{
        |  "plan": {
        |    "$type": "protocatalyst.plan.ProtoLogicalPlan.Aggregate",
        |    "groupingExprs": [
        |      {
        |        "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |        "name": "name",
        |        "qualifier": null,
        |        "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |        "nullable": true
        |      }
        |    ],
        |    "aggregateExprs": [
        |      {
        |        "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |        "name": "name",
        |        "qualifier": null,
        |        "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |        "nullable": true
        |      },
        |      {
        |        "$type": "protocatalyst.expr.ProtoExpr.Count",
        |        "children": []
        |      }
        |    ],
        |    "child": {
        |      "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |      "name": "users",
        |      "alias": null,
        |      "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |    }
        |  }
        |}""".stripMargin

    val result = ParityTester.testParity(sql, json)
    assert(result.protoPlan != null)
    assert(result.sparkPlan != null)
  }

  test("parity: UNION") {
    implicit val s: SparkSession = spark
    val sql = "SELECT name FROM users UNION SELECT name FROM users"

    val json =
      """{
        |  "plan": {
        |    "$type": "protocatalyst.plan.ProtoLogicalPlan.Union",
        |    "children": [
        |      {
        |        "$type": "protocatalyst.plan.ProtoLogicalPlan.Project",
        |        "projectList": [
        |          {
        |            "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |            "name": "name",
        |            "qualifier": null,
        |            "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |            "nullable": true
        |          }
        |        ],
        |        "child": {
        |          "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |          "name": "users",
        |          "alias": null,
        |          "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |        }
        |      },
        |      {
        |        "$type": "protocatalyst.plan.ProtoLogicalPlan.Project",
        |        "projectList": [
        |          {
        |            "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |            "name": "name",
        |            "qualifier": null,
        |            "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |            "nullable": true
        |          }
        |        ],
        |        "child": {
        |          "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |          "name": "users",
        |          "alias": null,
        |          "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |        }
        |      }
        |    ],
        |    "byName": false,
        |    "allowMissingColumns": false
        |  }
        |}""".stripMargin

    val result = ParityTester.testParity(sql, json)
    assert(result.protoPlan != null)
    assert(result.sparkPlan != null)
  }

  test("parity: CTE") {
    implicit val s: SparkSession = spark
    val sql = "WITH active AS (SELECT name FROM users WHERE age > 18) SELECT * FROM active"

    val json =
      """{
        |  "plan": {
        |    "$type": "protocatalyst.plan.ProtoLogicalPlan.With",
        |    "cteRelations": [
        |      ["active", {
        |        "$type": "protocatalyst.plan.ProtoLogicalPlan.SubqueryAlias",
        |        "alias": "active",
        |        "child": {
        |          "$type": "protocatalyst.plan.ProtoLogicalPlan.Project",
        |          "projectList": [
        |            {
        |              "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |              "name": "name",
        |              "qualifier": null,
        |              "dataType": {"$type": "protocatalyst.types.ProtoType.StringType"},
        |              "nullable": true
        |            }
        |          ],
        |          "child": {
        |            "$type": "protocatalyst.plan.ProtoLogicalPlan.Filter",
        |            "condition": {
        |              "$type": "protocatalyst.expr.ProtoExpr.Gt",
        |              "left": {
        |                "$type": "protocatalyst.expr.ProtoExpr.ColumnRef",
        |                "name": "age",
        |                "qualifier": null,
        |                "dataType": {"$type": "protocatalyst.types.ProtoType.IntegerType"},
        |                "nullable": false
        |              },
        |              "right": {
        |                "$type": "protocatalyst.expr.ProtoExpr.Literal",
        |                "value": {"$type": "protocatalyst.expr.LiteralValue.IntValue", "value": 18}
        |              }
        |            },
        |            "child": {
        |              "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |              "name": "users",
        |              "alias": null,
        |              "schema": {"tableName": "users", "fields": [], "fingerprint": 0}
        |            }
        |          }
        |        }
        |      }]
        |    ],
        |    "recursive": false,
        |    "child": {
        |      "$type": "protocatalyst.plan.ProtoLogicalPlan.RelationRef",
        |      "name": "active",
        |      "alias": null,
        |      "schema": {"tableName": "active", "fields": [], "fingerprint": 0}
        |    }
        |  }
        |}""".stripMargin

    val result = ParityTester.testParity(sql, json)
    assert(result.protoPlan != null)
    assert(result.sparkPlan != null)
  }
}
